import type { CustomerEvent, CustomerProfile } from "../types";

/** DEMO DATA — 고객 프로필 (재구매 후보 분석용 최소 필드) */
export const demoCustomers: CustomerProfile[] = [
  {
    id: "cu-01",
    name: "김O연 (Demo)",
    joinedAt: "2024-08-12",
    lastOrderAt: "2025-03-02",
    orderCount: 6,
    favoriteProducts: ["p-ess-01", "p-crm-01"],
    concerns: ["수분", "진정"],
    repurchaseDue: true,
  },
  {
    id: "cu-02",
    name: "이O진 (Demo)",
    joinedAt: "2024-11-03",
    lastOrderAt: "2025-04-15",
    orderCount: 3,
    favoriteProducts: ["p-amp-50"],
    concerns: ["탄력"],
    repurchaseDue: true,
  },
  {
    id: "cu-03",
    name: "박O수 (Demo)",
    joinedAt: "2025-01-20",
    lastOrderAt: "2025-05-20",
    orderCount: 2,
    favoriteProducts: ["p-ton-01", "p-msk-01"],
    concerns: ["수분", "피부결"],
    repurchaseDue: false,
  },
  {
    id: "cu-04",
    name: "최O아 (Demo)",
    joinedAt: "2024-06-30",
    lastOrderAt: "2025-02-14",
    orderCount: 8,
    favoriteProducts: ["p-crm-01", "p-cln-01"],
    concerns: ["진정", "데일리 케어"],
    repurchaseDue: true,
  },
  {
    id: "cu-05",
    name: "정O민 (Demo)",
    joinedAt: "2025-03-05",
    lastOrderAt: "2025-05-25",
    orderCount: 1,
    favoriteProducts: ["p-amp-30"],
    concerns: ["광채"],
    repurchaseDue: false,
  },
];

/** DEMO DATA — Customer Front 행동 데이터 (최근 30일 집계) */
export const demoCustomerEvents: CustomerEvent[] = [
  { productId: "p-amp-50", type: "view", count: 4820 },
  { productId: "p-amp-50", type: "wishlist", count: 692 },
  { productId: "p-amp-50", type: "finder_complete", count: 415 },
  { productId: "p-ess-01", type: "view", count: 4310 },
  { productId: "p-ess-01", type: "wishlist", count: 540 },
  { productId: "p-ess-01", type: "finder_complete", count: 386 },
  { productId: "p-crm-01", type: "view", count: 2980 },
  { productId: "p-crm-01", type: "wishlist", count: 310 },
  { productId: "p-crm-01", type: "finder_complete", count: 242 },
  { productId: "p-amp-30", type: "view", count: 2540 },
  { productId: "p-amp-30", type: "wishlist", count: 355 },
  { productId: "p-amp-30", type: "finder_complete", count: 198 },
  { productId: "p-ton-01", type: "view", count: 1980 },
  { productId: "p-ton-01", type: "wishlist", count: 205 },
  { productId: "p-msk-01", type: "view", count: 1720 },
  { productId: "p-msk-01", type: "wishlist", count: 186 },
  { productId: "p-crm-02", type: "view", count: 1450 },
  { productId: "p-crm-02", type: "wishlist", count: 240 },
  { productId: "p-crm-02", type: "finder_complete", count: 130 },
  { productId: "p-cln-01", type: "view", count: 1210 },
  { productId: "p-sun-01", type: "view", count: 640 },
  { productId: "p-mst-01", type: "view", count: 410 },
];
