import type { Product } from "../types";

/**
 * DEMO DATA — 실제 가연인터내셔널 제품 자료 수령 후 교체 예정.
 * 제품명은 제품 유형 기반 Placeholder이며, 근거 없는 효능·성분 표현을 포함하지 않는다.
 */
export const demoProducts: Product[] = [
  {
    id: "p-ess-01",
    name: "미려 트리트먼트 에센스",
    nameEn: "MIRYEO Treatment Essence 150ml",
    sku: "MRY-ESS-01",
    category: "에센스/앰플",
    line: "하이드로 라인",
    price: 52000,
    cost: 14500,
    status: "성장",
    mainChannels: ["ch-direct", "ch-online", "ch-hnb"],
    description: "촉촉한 수분 결 케어를 위한 데일리 에센스 (Demo)",
    concerns: ["수분", "피부결"],
    texture: "가벼움",
    routineStep: 2,
    rating: 4.8,
    reviewCount: 1234,
    isBest: true,
  },
  {
    id: "p-amp-50",
    name: "미려 인텐시브 앰플",
    nameEn: "MIRYEO Intensive Ampoule 50ml",
    sku: "MRY-AMP-50",
    category: "에센스/앰플",
    line: "인텐시브 라인",
    price: 68000,
    cost: 19000,
    status: "성장",
    mainChannels: ["ch-direct", "ch-online", "ch-live"],
    description: "피부 탄력과 영양 집중 케어 앰플 (Demo)",
    concerns: ["탄력", "광채"],
    texture: "중간",
    routineStep: 2,
    rating: 4.9,
    reviewCount: 866,
    isBest: true,
  },
  {
    id: "p-crm-01",
    name: "미려 수딩 크림",
    nameEn: "MIRYEO Soothing Cream 80ml",
    sku: "MRY-CRM-01",
    category: "크림",
    line: "카밍 라인",
    price: 38000,
    cost: 10500,
    status: "안정",
    mainChannels: ["ch-online", "ch-hnb", "ch-b2b"],
    description: "예민해진 피부를 편안하게 진정시키는 수분 크림 (Demo)",
    concerns: ["진정", "수분"],
    texture: "중간",
    routineStep: 3,
    rating: 4.8,
    reviewCount: 957,
  },
  {
    id: "p-cln-01",
    name: "미려 카밍 클렌저",
    nameEn: "MIRYEO Calming Cleanser 150ml",
    sku: "MRY-CLN-01",
    category: "클렌저",
    line: "카밍 라인",
    price: 28000,
    cost: 7200,
    status: "안정",
    mainChannels: ["ch-online", "ch-hnb"],
    description: "저자극 약산성 데일리 클렌저 (Demo)",
    concerns: ["데일리 케어", "진정"],
    texture: "가벼움",
    routineStep: 1,
    rating: 4.7,
    reviewCount: 654,
  },
  {
    id: "p-ton-01",
    name: "미려 하이드로 토너",
    nameEn: "MIRYEO Hydro Toner 200ml",
    sku: "MRY-TON-01",
    category: "토너/미스트",
    line: "하이드로 라인",
    price: 32000,
    cost: 8800,
    status: "성장",
    mainChannels: ["ch-direct", "ch-online"],
    description: "피부 결을 정돈하는 수분 토너 (Demo)",
    concerns: ["수분", "피부결"],
    texture: "가벼움",
    routineStep: 1,
    rating: 4.7,
    reviewCount: 512,
  },
  {
    id: "p-sun-01",
    name: "미려 데일리 선크림",
    nameEn: "MIRYEO Daily Sun Cream 50ml",
    sku: "MRY-SUN-01",
    category: "선케어",
    line: "데일리 라인",
    price: 26000,
    cost: 7500,
    status: "부진",
    mainChannels: ["ch-online", "ch-hnb"],
    description: "가볍게 마무리되는 데일리 선케어 (Demo)",
    concerns: ["데일리 케어"],
    texture: "가벼움",
    routineStep: 4,
    rating: 4.6,
    reviewCount: 438,
  },
  {
    id: "p-msk-01",
    name: "미려 시트 마스크",
    nameEn: "MIRYEO Sheet Mask (5ea)",
    sku: "MRY-MSK-01",
    category: "마스크",
    line: "하이드로 라인",
    price: 24000,
    cost: 6000,
    status: "안정",
    mainChannels: ["ch-online", "ch-live", "ch-export"],
    description: "수분 충전 집중 케어 시트 마스크 (Demo)",
    concerns: ["수분", "진정"],
    texture: "가벼움",
    routineStep: 2,
    rating: 4.7,
    reviewCount: 720,
  },
  {
    id: "p-amp-30",
    name: "미려 브라이트 앰플",
    nameEn: "MIRYEO Bright Ampoule 30ml",
    sku: "MRY-AMP-30",
    category: "에센스/앰플",
    line: "인텐시브 라인",
    price: 45000,
    cost: 12800,
    status: "성장",
    mainChannels: ["ch-direct", "ch-online"],
    description: "맑고 환한 피부 톤 케어 앰플 (Demo)",
    concerns: ["광채", "피부결"],
    texture: "가벼움",
    routineStep: 2,
    rating: 4.8,
    reviewCount: 389,
    isNew: true,
  },
  {
    id: "p-crm-02",
    name: "미려 탄력 크림",
    nameEn: "MIRYEO Firming Cream 50ml",
    sku: "MRY-CRM-02",
    category: "크림",
    line: "인텐시브 라인",
    price: 58000,
    cost: 16500,
    status: "신규",
    mainChannels: ["ch-direct", "ch-b2b"],
    description: "탄탄한 피부 탄력 케어 크림 (Demo)",
    concerns: ["탄력"],
    texture: "리치",
    routineStep: 3,
    rating: 4.9,
    reviewCount: 112,
    isNew: true,
  },
  {
    id: "p-mst-01",
    name: "미려 페이스 미스트",
    nameEn: "MIRYEO Face Mist 120ml",
    sku: "MRY-MST-01",
    category: "토너/미스트",
    line: "데일리 라인",
    price: 22000,
    cost: 5800,
    status: "부진",
    mainChannels: ["ch-online"],
    description: "언제 어디서나 수분 충전 미스트 (Demo)",
    concerns: ["수분", "데일리 케어"],
    texture: "가벼움",
    routineStep: 1,
    rating: 4.5,
    reviewCount: 267,
  },
];
